spring:
  application:
    name: front-notification-service
  rabbitmq:
    host: localhost
    username: avdey
    password: 61Ifhjukjn$
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
      port: 8086
rabbit:
  queueFrontIn: front.in
  queueTelegramIn: telegram.in
bot:
  token: 7487503506:AAHs3DkvFz_8uzo8mY_XWSUEv5s-6io4qGc
  name: Cnttops_bot
  receivers:
    - 1345063137
    - 267239507